channels:
  - simpleitk
  - conda-forge
dependencies:
  - python==3.8
  - numpy>=1.21
  - h5py==2.10
  - SimpleITK>=2.0
  - hdf5storage>=0.1
  - nibabel>=3.2
  - numba>=0.52
  - py-opencv>=4.5
  - pip
  - scipy>=1.7.3
  - tqdm>=4.64.0
  - typing_extensions>=4.2.0
  - pip:
    - torch==1.11.0